version: '3'

vars:
  MODULE_NAME: "SubSys"

includes:
  version: ../Taskfile.version.yml
  production: ../Taskfile.prod.yml

tasks:
  default:
    desc: "Development build of the {{.MODULE_NAME}} module"
    cmds:
      - echo "Building {{.MODULE_NAME}} module..."
      - go mod download
      - go mod verify
      - go mod tidy
      - go vet ./...
      - go build ./...
      - go test -race -run Test ./...
      - task: clean
      - echo "✓ {{.MODULE_NAME}} module build complete"

  prod:
    cmds:
      - task: production:prod

  clean:
    desc: "Clean up build artifacts"
    cmds:
      - rm -rf ./relative
      - rm -r ./data
      - echo "Build artifacts cleaned"
#
#  docker:start:
#    desc: "Start Docker containers for {{.MODULE_NAME}}"
#    dir: ./postgres
#    cmds:
#      - docker-compose up -d
#      - echo "✓ Docker containers started"
#
#  docker:stop:
#    desc: "Stop Docker containers for {{.MODULE_NAME}}"
#    dir: ./postgres
#    cmds:
#      - docker-compose stop
#      - echo "✓ Docker containers stopped"
#
#  docker:cleanup:
#    desc: "Stop and remove Docker containers, networks, and volumes"
#    dir: ./postgres
#    cmds:
#      - docker-compose down -v
#      - echo "✓ Docker cleanup complete"
